# Los Fundamentos de los Arrays en Numpy

## Atributos de Numpy Array

In [ ]:
import numpy as np
rng = np.random.default_rng(seed=1701)

In [ ]:
x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3,4))
x3 = rng.integers(10, size=(3, 4, 5))

In [ ]:
print(x1)

[9 4 0 3 8 6]


In [ ]:
print(x2)

[[2 3 0 0]
 [6 9 4 3]
 [5 5 0 8]]


In [ ]:
print(x3)

[[[4 3 9 9 2]
  [2 4 0 0 3]
  [0 0 2 3 2]
  [7 4 7 9 3]]

 [[6 6 5 0 2]
  [5 6 4 8 2]
  [5 6 2 7 3]
  [8 9 2 7 2]]

 [[5 3 6 8 2]
  [0 6 5 8 4]
  [3 2 4 3 9]
  [2 3 6 1 3]]]


In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size:", x3.size)
print("dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size: 60
dtype:  int64


## Indexación del Array

In [ ]:
x1

array([3, 1, 2, 5, 6, 2])

In [ ]:
x1[0]

3

In [ ]:
x1[4]

6

In [ ]:
x1[-1]

2

In [ ]:
x1[-2]

6

In [ ]:
x2

array([[5, 2, 7, 9],
       [3, 5, 6, 0],
       [2, 0, 2, 9]])

In [ ]:
x2[0,0]

5

In [ ]:
x2[2, 0]

2

In [ ]:
x2[2, -1]

9

In [ ]:
x2[0,0] = 12
x2

array([[12,  2,  7,  9],
       [ 3,  5,  6,  0],
       [ 2,  0,  2,  9]])

In [ ]:
x1[0] = 3.1415 # No se van a guardar los decimales
x1

array([3, 1, 2, 5, 6, 2])

## Slicing del Array: Accediendo a Subarrays


In [ ]:
x1

array([3, 1, 2, 5, 6, 2])

In [ ]:
x1[:3]

array([3, 1, 2])

In [ ]:
x1[3:]

array([5, 6, 2])

In [ ]:
x1[1:4]

array([1, 2, 5])

In [ ]:
x1[::2]

array([3, 2, 6])

In [ ]:
x1[1::2]

array([1, 5, 2])

In [ ]:
x1[::-1]

array([2, 6, 5, 2, 1, 3])

In [ ]:
x1[4::-2]

array([6, 2, 3])

In [ ]:
x2

array([[12,  2,  7,  9],
       [ 3,  5,  6,  0],
       [ 2,  0,  2,  9]])

In [ ]:
x2[:2, :3]

array([[12,  2,  7],
       [ 3,  5,  6]])

In [ ]:
x2[:3, ::2]

array([[12,  7],
       [ 3,  6],
       [ 2,  2]])

In [ ]:
x2[:,0]

array([12,  3,  2])

In [ ]:
x2[0,:]

array([12,  2,  7,  9])

In [ ]:
x2[0]

array([12,  2,  7,  9])

In [ ]:
print(x2)

[[12  2  7  9]
 [ 3  5  6  0]
 [ 2  0  2  9]]


In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  2]
 [ 3  5]]


In [ ]:
x2_sub[0,0] = 30
print(x2_sub)

[[30  2]
 [ 3  5]]


In [ ]:
print(x2)

[[30  2  7  9]
 [ 3  5  6  0]
 [ 2  0  2  9]]


## Creando copias de Arrays

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[30  2]
 [ 3  5]]


In [ ]:
x2_sub_copy[0,0] = 50
print(x2_sub_copy)

[[50  2]
 [ 3  5]]


In [ ]:
print(x2) # No se ha modificado

[[30  2  7  9]
 [ 3  5  6  0]
 [ 2  0  2  9]]


## Reshape de Arrays

In [ ]:
grid = np.arange(1,10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # Vector Fila

array([[1, 2, 3]])

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
x.reshape((3, 1)) # Vector Columna

array([[1],
       [2],
       [3]])

In [ ]:
x[np.newaxis, :] # Vector fila

array([[1, 2, 3]])

In [ ]:
x[:, np.newaxis] # Vector columna

array([[1],
       [2],
       [3]])

### 💡 Explicación detallada de np.newaxis

Cuando tienes un array unidimensional como `x = np.array([1, 2, 3])` con forma (3,), a veces necesitas convertirlo en un array bidimensional, ya sea como:

1. Un **vector fila** con forma (1, 3) - una fila, tres columnas
2. Un **vector columna** con forma (3, 1) - tres filas, una columna

Hay dos formas principales de hacer esto:

#### 1. Usando reshape()
```python
x.reshape(1, 3)  # Vector fila: [[1, 2, 3]]
x.reshape(3, 1)  # Vector columna: [[1], [2], [3]]
```

#### 2. Usando np.newaxis
```python
x[np.newaxis, :]  # Vector fila: inserta un nuevo eje en la posición 0
x[:, np.newaxis]  # Vector columna: inserta un nuevo eje en la posición 1
```

### ¿Cómo funciona np.newaxis?

- `np.newaxis` es simplemente un alias para `None` en el contexto de la indexación
- Cuando lo colocas dentro de los corchetes de indexación, le indica a NumPy que debe insertar una dimensión de tamaño 1 en esa posición

### Ejemplo paso a paso

Tomemos el array `x = np.array([1, 2, 3])` con forma (3,):

1. **Creando un vector fila** (1×3):
   ```python
   row_vector = x[np.newaxis, :]
   # o equivalentemente: x[None, :]
   ```
   
   - La forma cambia de (3,) a (1, 3)
   - Se visualiza como: `[[1, 2, 3]]`
   - El primer índice ahora selecciona filas (solo hay una)
   - El segundo índice selecciona columnas

2. **Creando un vector columna** (3×1):
   ```python
   column_vector = x[:, np.newaxis]
   # o equivalentemente: x[:, None]
   ```
   
   - La forma cambia de (3,) a (3, 1)
   - Se visualiza como: `[[1], [2], [3]]`
   - El primer índice selecciona filas
   - El segundo índice selecciona columnas (solo hay una)

### ¿Por qué es útil?

Esta técnica es extremadamente útil en muchos contextos:

1. **Broadcasting**: Permite realizar operaciones entre arrays de diferentes dimensiones
2. **Álgebra lineal**: Facilita la diferenciación entre vectores fila y columna
3. **Procesamiento de datos**: A menudo necesitas añadir una dimensión para procesar datos en lotes
4. **Visualización**: Algunas funciones esperan entradas con dimensiones específicas

### Ejemplo práctico de uso

```python
# Tenemos dos arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Queremos calcular el producto externo (outer product)
# Para esto, necesitamos convertirlos en vector columna y vector fila
outer_product = x[:, np.newaxis] * y  # o x.reshape(3, 1) * y

# El resultado será una matriz 3×3:
# [[ 4,  5,  6],
#  [ 8, 10, 12],
#  [12, 15, 18]]
```

## Concatenación y Splitting de Array

### Concatenación de Arrays


In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
z  = [20, 30, 40]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 20 30 40]


In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting Arrays

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # Indicándole que los cortes van en el índice 3 y 5
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Ejercicios de Repaso: Fundamentos de Arrays NumPy

## Ejercicio 1: Manipulación básica de arrays

En este ejercicio trabajarás con las operaciones básicas de creación, indexación y modificación de arrays NumPy.

```python
import numpy as np
np.random.seed(42)  # Para reproducibilidad

# 1.1 Crea un array unidimensional con los números del 1 al 10
# Tu código aquí

# 1.2 Crea un array bidimensional de tamaño 3x4 con números aleatorios enteros entre 0 y 100
# Tu código aquí

# 1.3 Accede al elemento en la posición (1,2) del array bidimensional
# Tu código aquí

# 1.4 Modifica todos los elementos de la primera fila del array bidimensional para que sean igual a 0
# Tu código aquí

# 1.5 Imprime los atributos ndim, shape, size y dtype del array bidimensional
# Tu código aquí
```

## Ejercicio 2: Slicing y vistas de arrays

Este ejercicio te ayudará a comprender mejor el funcionamiento del slicing en NumPy y la diferencia entre vistas y copias de arrays.

```python
import numpy as np

# Crea una matriz de 5x5 con valores del 1 al 25
matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz original:")
print(matriz)

# 2.1 Extrae una submatriz de 3x3 que contenga los elementos centrales de la matriz original
# Tu código aquí

# 2.2 Modifica todos los elementos de la submatriz para que sean igual a 0 y observa qué pasa con la matriz original
# Tu código aquí

# 2.3 Ahora crea una copia explícita de la submatriz central (3x3)
# Tu código aquí

# 2.4 Modifica los elementos de la copia para que sean igual a 99 y verifica que la matriz original no cambia
# Tu código aquí

# 2.5 Extrae la última columna de la matriz original
# Tu código aquí

# 2.6 Extrae las filas pares de la matriz original (filas 0, 2, 4)
# Tu código aquí
```

## Ejercicio 3: Concatenación, división y reshape de arrays

Este ejercicio se centra en las operaciones de unión, división y cambio de forma de arrays NumPy.

```python
import numpy as np

# 3.1 Crea dos arrays:
# - Un array 'a' de forma (3,2) con valores del 1 al 6
# - Un array 'b' de forma (3,2) con valores del 7 al 12
# Tu código aquí

# 3.2 Concatena los arrays 'a' y 'b' horizontalmente (a lo largo del eje 1)
# Tu código aquí

# 3.3 Concatena los arrays 'a' y 'b' verticalmente (a lo largo del eje 0)
# Tu código aquí

# 3.4 Crea un array unidimensional 'c' con valores del 1 al 12
# Tu código aquí

# 3.5 Utiliza reshape para convertir 'c' en un array de forma (4,3)
# Tu código aquí

# 3.6 Divide el array del paso anterior en 2 arrays de forma (2,3) usando np.split
# Tu código aquí

# 3.7 Crea un array unidimensional 'd' con valores del 1 al 3 y conviértelo en:
# - Un vector fila (forma 1x3) usando np.newaxis
# - Un vector columna (forma 3x1) usando np.newaxis
# Tu código aquí

# 3.8 Crea una matriz 4x4 con valores del 1 al 16 y divídela en 4 submatrices de 2x2 usando vsplit y hsplit
# Tu código aquí
```


In [ ]:
import numpy as np
np.random.seed(42)
# np.random.randint

### Soluciones

#### Solucones Ejercicio 1

In [ ]:
# 1.1 Crea un array unidimensional con los números del 1 al 10
arr1d = np.arange(1, 11)
print(arr1d)

# 1.2 Crea un array bidimensional de tamaño 3x4 con números aleatorios enteros entre 0 y 100
arr2d = np.random.randint(0, 101, size=(3, 4))
print(arr2d)

# 1.3 Accede al elemento en la posición (1,2) del array bidimensional
elemento = arr2d[1, 2]
print(elemento)

# 1.4 Modifica todos los elementos de la primera fila del array bidimensional para que sean igual a 0
arr2d[0,:] = 0
print(arr2d)

# 1.5 Imprime los atributos ndim, shape, size y dtype del array bidimensional
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
[[23  2 21 52]
 [ 1 87 29 37]
 [ 1 63 59 20]]
29
[[ 0  0  0  0]
 [ 1 87 29 37]
 [ 1 63 59 20]]
2
(3, 4)
12
int64


#### Soluciones Ejericio 2

In [ ]:
import numpy as np

# Crea una matriz de 5x5 con valores del 1 al 25
matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz original:")
print(matriz)

# 2.1 Extrae una submatriz de 3x3 que contenga los elementos centrales de la matriz original
submatriz = matriz[1:4, 1:4]
print(submatriz)

# 2.2 Modifica todos los elementos de la submatriz para que sean igual a 0 y observa qué pasa con la matriz original
submatriz[:] = 0
print("Matriz original después de modificar la submatriz:")
print(matriz)
print(submatriz)

# 2.3 Ahora crea una copia explícita de la submatriz central (3x3)
matriz = np.arange(1, 26).reshape(5, 5)
submatriz = matriz[1:4, 1:4].copy()
print(submatriz)

# 2.4 Modifica los elementos de la copia para que sean igual a 99 y verifica que la matriz original no cambia
submatriz[:] = 99
print("Matriz original después de modificar la copia:")
print(matriz)
print(submatriz)

# 2.5 Extrae la última columna de la matriz original
ultima_columna = matriz[:, -1]
print(ultima_columna)

# 2.6 Extrae las filas pares de la matriz original (filas 0, 2, 4)
filas_pares = matriz[::2]
print(filas_pares)

Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Matriz original después de modificar la submatriz:
[[ 1  2  3  4  5]
 [ 6  0  0  0 10]
 [11  0  0  0 15]
 [16  0  0  0 20]
 [21 22 23 24 25]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Matriz original después de modificar la copia:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]
[ 5 10 15 20 25]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


#### Soluciones Ejercicio 3

In [ ]:
# 3.1 Crea dos arrays:
# - Un array 'a' de forma (3,2) con valores del 1 al 6
# - Un array 'b' de forma (3,2) con valores del 7 al 12
a = np.arange(1, 7).reshape(3, 2)
b = np.arange(7, 13).reshape(3, 2)
print(a)
print(b)

# 3.2 Concatena los arrays 'a' y 'b' horizontalmente (a lo largo del eje 1)
c_horizontal = np.concatenate([a, b], axis=1)
print(c_horizontal)

# 3.3 Concatena los arrays 'a' y 'b' verticalmente (a lo largo del eje 0)
c_vertical = np.concatenate([a, b], axis=0)
print(c_vertical)

# 3.4 Crea un array unidimensional 'c' con valores del 1 al 12
c = np.arange(1, 13)
print(c)

# 3.5 Utiliza reshape para convertir 'c' en un array de forma (4,3)
c_reshaped = c.reshape(4, 3)
print(c_reshaped)

# 3.6 Divide el array del paso anterior en 2 arrays de forma (2,3) usando np.split
c_split1, c_split2 = np.split(c_reshaped, 2)
print(c_split1)
print(c_split2)

# 3.7 Crea un array unidimensional 'd' con valores del 1 al 3 y conviértelo en:
# - Un vector fila (forma 1x3) usando np.newaxis
# - Un vector columna (forma 3x1) usando np.newaxis
d = np.arange(1, 4)
d_fila = d[np.newaxis, :]
d_columna = d[:, np.newaxis]
print(d)
print(d_fila)
print(d_columna)

# 3.8 Crea una matriz 4x4 con valores del 1 al 16 y divídela en 4 submatrices de 2x2 usando vsplit y hsplit
matriz_4x4 = np.arange(1, 17).reshape(4, 4)
print(matriz_4x4)

# Primero dividimos en dos partes horizontal y verticalmente
top, bottom = np.vsplit(matriz_4x4, 2)
print(top)
print(bottom)

# Ahora dividimos cada parte en izquierda y derecha
top_left, top_right = np.hsplit(top, 2)
bottom_left, bottom_right = np.hsplit(bottom, 2)

print(top_left)
print(top_right)
print(bottom_left)
print(bottom_right)


[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


In [ ]:
# 3.6 Divide el array del paso anterior en 2 arrays de forma (2,3) usando np.split
c_split1, c_split2 = np.split(c_reshaped, 2)
print(c_split1)
print(c_split2)

In [ ]:
c_reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.split(c_reshaped, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [ ]:
np.split(c_reshaped, 4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

In [ ]:
np.split(c_reshaped, 3)

ValueError: array split does not result in an equal division

In [ ]:
np.split(c_reshaped, [2, 3])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]